# This is a basic workflow to help you get started with Actions
# Aqui você pode dar o nome do workflow
name: Meu Workflow
# Controls when the workflow will run
# Informa quando o workflow sera disparado (Ativado)
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Qualquer push na main
  push:
    branches: [ "main" ]
  # Qualquer PR para a main
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # Permite que o workflow seja ativado de forma manual caso necessario
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Nome do Job
  build:
    # The type of runner that the job will run on
    # Define onde o job sera inicializado (Mac - Windows - Ubunto)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Pega o workflow
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
      # Run => Executa uma linha de comando!
        run: echo Hello, world teste!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
